//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTO()
        {
            this.PENDENCIAS = new HashSet<PENDENCIA>();
            this.RESULTADOS_VOTACOES = new HashSet<RESULTADOS_VOTACOES>();
        }
    
        public int id { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> usuario { get; set; }
        public System.DateTime data { get; set; }
        public bool estado { get; set; }
        public int tipo { get; set; }
    
        public virtual ITEN ITEN { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENDENCIA> PENDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADOS_VOTACOES> RESULTADOS_VOTACOES { get; set; }
    }
}
