//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamApi.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAMEntities : DbContext
    {
        public SAMEntities()
            : base("name=SAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOS { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<EVENTO> EVENTOS { get; set; }
        public virtual DbSet<ITEN> ITENS { get; set; }
        public virtual DbSet<PENDENCIA> PENDENCIAS { get; set; }
        public virtual DbSet<RESULTADOS_VOTACOES> RESULTADOS_VOTACOES { get; set; }
        public virtual DbSet<TAGGED_ITENS> TAGGED_ITENS { get; set; }
        public virtual DbSet<TAG> TAGS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
    }
}
