//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGGED_ITENS
    {
        public int id { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> tag { get; set; }
    
        public virtual ITEN ITEN { get; set; }
        public virtual TAG TAG { get; set; }
    }
}
