//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.EVENTOS = new HashSet<EVENTO>();
            this.PENDENCIAS = new HashSet<PENDENCIA>();
            this.RESULTADOS_VOTACOES = new HashSet<RESULTADOS_VOTACOES>();
        }
    
        public int id { get; set; }
        public Nullable<int> cargo { get; set; }
        public int pontos { get; set; }
        public string samaccount { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string redes { get; set; }
        public System.DateTime dataInicio { get; set; }
        public byte[] foto { get; set; }
        public bool ativo { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTO> EVENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENDENCIA> PENDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADOS_VOTACOES> RESULTADOS_VOTACOES { get; set; }
    }
}
