//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamDataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Pendencias = new HashSet<Pendencia>();
            this.ResultadoVotacoes = new HashSet<ResultadoVotacao>();
        }
    
        public int id { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public bool estado { get; set; }
        public bool processado { get; set; }
        public string tipo { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pendencia> Pendencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoVotacao> ResultadoVotacoes { get; set; }
    }
}
