//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamDataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocao
    {
        public int id { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> cargoanterior { get; set; }
        public Nullable<int> cargoadquirido { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual Cargo CargoAnterior { get; set; }
        public virtual Cargo CargoAdquirido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
