//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamDataBase.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SamEntities : DbContext
    {
        public SamEntities()
            : base("name=SamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItensTagged> ItensTaggeds { get; set; }
        public virtual DbSet<Pendencia> Pendencias { get; set; }
        public virtual DbSet<ResultadoVotacao> ResultadoVotacaos { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Promocao> Promocaos { get; set; }
    }
}
