INSERT INTO CARGOS VALUES('Estagiário', NULL, 0);
INSERT INTO CARGOS VALUES('Técnico', NULL, 0);
INSERT INTO CARGOS VALUES('Júnior 1', NULL, 60);

INSERT INTO CARGOS VALUES('Júnior 2', 3, 60);
INSERT INTO CARGOS VALUES('Júnior 3', 4, 60);

INSERT INTO CARGOS VALUES('Sênior 1', 5, 120);
INSERT INTO CARGOS VALUES('Sênior 2', 6, 120);
INSERT INTO CARGOS VALUES('Sênior 3', 7, 120);

INSERT INTO CARGOS VALUES('Pleno 1', 8, 180);
INSERT INTO CARGOS VALUES('Pleno 2', 9, 180);
INSERT INTO CARGOS VALUES('Pleno 3', 10, 180);



