CREATE TABLE CARGOS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR(50) UNIQUE NOT NULL,
	anterior INT REFERENCES CARGOS(id) ON DELETE NO ACTION
);

CREATE TABLE USUARIOS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	cargo INT FOREIGN KEY REFERENCES CARGOS(id) ON DELETE NO ACTION,
	pontos INT NOT NULL DEFAULT 0,
	samaccount VARCHAR(50) UNIQUE NOT NULL,
	nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(200),
	redes VARCHAR(200),
	dataInicio DATE NOT NULL,
	foto BINARY,
	ativo BIT NOT NULL DEFAULT 1
);

CREATE TABLE CATEGORIAS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR(50) UNIQUE NOT NULL,
	peso INT NOT NULL
);

CREATE TABLE TAGS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	descricao VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ITENS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(200),
	dificuldade INT NOT NULL CHECK(dificuldade IN (1,3,8)),
	modificador INT NOT NULL CHECK(modificador IN (1,2,3,8)),
	categoria INT FOREIGN KEY REFERENCES CATEGORIAS(id) ON DELETE NO ACTION,
);

CREATE TABLE TAGGED_ITENS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	item INT FOREIGN KEY REFERENCES ITENS(id) ON DELETE CASCADE,
	tag  INT FOREIGN KEY REFERENCES TAGS(id) ON DELETE CASCADE
);

CREATE TABLE EVENTOS
(
	id INT IDENTITY(1,1) PRIMARY KEY,

	-- assunto do evento
	item INT FOREIGN KEY REFERENCES ITENS(id) ON DELETE NO ACTION,

	-- usuário que gerou o evento (possivelmente quem precisa ganhar pontos)
	usuario INT FOREIGN KEY REFERENCES USUARIOS(id) ON DELETE NO ACTION,

	data DATE NOT NULL,
	estado BIT NOT NULL DEFAULT 0,
	tipo INT NOT NULL CHECK(tipo IN ('votacao','atribuicao','promocao','agendamento')),
);

CREATE TABLE PENDENCIAS
(
	id INT IDENTITY(1,1) PRIMARY KEY,

	-- usuário a qual a pendência foi atribuída
	usuario INT FOREIGN KEY REFERENCES USUARIOS(id) ON DELETE CASCADE,

	-- evento do qual se trata a pendência
	evento INT FOREIGN KEY REFERENCES EVENTOS(id) ON DELETE CASCADE,

	-- diz se essa pendência foi ou nao resolvida
	estado BIT NOT NULL DEFAULT 1,
);


CREATE TABLE RESULTADOS_VOTACOES
(
	id INT IDENTITY(1,1) PRIMARY KEY,

	-- evento sendo votado
	evento INT FOREIGN KEY REFERENCES EVENTOS(id) ON DELETE NO ACTION,

	-- usuário que votou
	usuario INT FOREIGN KEY REFERENCES USUARIOS(id) ON DELETE NO ACTION,

	-- valor que foi votado
	dificuldade INT NOT NULL CHECK(dificuldade IN (1,3,8)),
	modificador INT NOT NULL CHECK(modificador IN (1,2,3,8))
);