INSERT INTO CARGOS VALUES('Estagiário', NULL);
INSERT INTO CARGOS VALUES('Técnico', NULL);
INSERT INTO CARGOS VALUES('Júnior 1', NULL);

INSERT INTO CARGOS VALUES('Júnior 2', 3);
INSERT INTO CARGOS VALUES('Júnior 3', 4);

INSERT INTO CARGOS VALUES('Sênior 1', 5);
INSERT INTO CARGOS VALUES('Sênior 2', 6);
INSERT INTO CARGOS VALUES('Sênior 3', 7);

INSERT INTO CARGOS VALUES('Pleno 1', 8);
INSERT INTO CARGOS VALUES('Pleno 2', 9);
INSERT INTO CARGOS VALUES('Pleno 3', 10);

select * from CARGOS

